# Generated by Django 4.2.7 on 2023-11-12 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drone_cones', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
