# Generated by Django 4.1.7 on 2023-12-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_cones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='orders_delivered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='drone',
            name='revenue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='orderCost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='drone',
            name='size',
            field=models.CharField(choices=[('large', 'Large'), ('medium', 'Medium'), ('small', 'Small')], max_length=100),
        ),
    ]
