# Generated by Django 4.1.7 on 2023-11-29 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drone_cones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='drone_cones.account'),
        ),
    ]
