# Generated by Django 4.1.7 on 2023-11-15 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drone_cones', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
