# Generated by Django 4.2.7 on 2023-11-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_cones', '0002_delete_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('flavor', models.CharField(max_length=100)),
                ('coneFlavor', models.CharField(max_length=100)),
                ('scoopCount', models.IntegerField()),
                ('stockAvailable', models.IntegerField()),
            ],
        ),
    ]
