# Generated by Django 4.1.7 on 2023-12-08 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_cones', '0002_drone_orders_delivered_drone_revenue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='companyCost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='netRevenue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drone',
            name='revenue',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
