# Generated by Django 4.1 on 2023-12-08 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_cones', '0002_drone_orders_delivered_drone_revenue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='revenue',
            field=models.FloatField(default=0),
        ),
    ]
