# Generated by Django 4.2.7 on 2023-11-21 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drone_cones', '0003_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='coneFlavor',
        ),
        migrations.RemoveField(
            model_name='products',
            name='scoopCount',
        ),
    ]
