# Generated by Django 4.1.7 on 2023-12-08 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_cones', '0003_products_companycost_products_netrevenue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='companyCost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='products',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='products',
            name='netRevenue',
            field=models.FloatField(default=0.0),
        ),
    ]
