# Generated by Django 4.1 on 2023-11-29 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_cones', '0005_alter_account_address_alter_account_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='account',
        ),
        migrations.AddField(
            model_name='orders',
            name='account_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='address2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='deliverySuccessful',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='drone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='items',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='timeDelivered',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='timeOrdered',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='timeToDeliver',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='zip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
