# Generated by Django 4.1.7 on 2023-11-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_cones', '0005_alter_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
